service: mailshrimp
app: mailshrimp
org: guilhermesfausto

frameworkVersion: '2'

provider:
  name: aws
  stage: dev
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: us-east-2
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: 
            - "sqs:*"
          Resource: "*"
  
  environment: 
    MS_URL_MESSAGES: ${param:MS_URL_MESSAGES}
    MS_JWT_SECRET: ${param:MS_JWT_SECRET}
    MS_JWT_EXPIRES: ${param:MS_JWT_EXPIRES}
  
  tags: 
    STAGE: prd
    PROJECT: mailshrimp 

  deploymentBucket:
    name: ${self:service}-deployment-fausto
    tags: 
      STAGE: ${self:provider.stage}
      PROJETO: ${self:service}

plugins:
  - serverless-layers
  
custom:
  serverless-layers:
    dependenciesPath: package.json
  

functions:
  send-message:
    name: ${opt:stage, self:provider.stage}-${self:service}-send-message
    handler: src/handlers/send-message/index.sendMessage
    description: "Envia o e-mail"
    memorySize: 128
    timeout: 60
    events: 
      - sqs:
          #arn: arn:aws:sqs:us-east-2:318435321320:mailshrimp-prod-fila-mensagens
          arn: arn:aws:sqs:us-east-2:318435321320:Mailshrimp.fifo
          batchSize: 1